import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import "../styles/Login.css";

export default function Register() {
  const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch("http://localhost:5000/api/auth/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Could not create account."); localStorage.setItem("user", JSON.stringify(data.user || { name: form.name, email: form.email })); navigate("/"); } catch (requestError) { if (requestError instanceof TypeError) { localStorage.setItem("user", JSON.stringify({ name: form.name, email: form.email })); navigate("/"); } else setError(requestError.message); } finally { setLoading(false); } };
  return <main className="auth-page"><div className="orb orb-one" /><div className="orb orb-two" /><form className="auth-card" onSubmit={submit}><div className="brand-mark">C</div><h1>Create account</h1><p>Join your people on ChatSphere.</p>{error && <div className="form-error">{error}</div>}<label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" required /></label><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" required /></label><label>Password<input type="password" minLength="6" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters" required /></label><button className="primary-btn" disabled={loading}>{loading ? "Creating…" : "Create account"}</button><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></form></main>;
}
